apiVersion: apps/v1
kind: Deployment
metadata:
  name: jasoseoai-nextjs-deployment
  labels:
    app: jasoseoai-nextjs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jasoseoai-nextjs
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jasoseoai-nextjs
    spec:
      containers:
      - name: jasoseoai-nextjs
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.image.port }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.image.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
