image:
  repository: 076831690411.dkr.ecr.ap-northeast-2.amazonaws.com/jasoseoai_nextjs
  tag: 11162f4617af700356bde91afdc48cfccac3a5bb
  port: 4000
service:
  name: jasoseoai-nextjs-service
  type: LoadBalancer
  port: 80
  targetPort: 4000
hpa:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilization: 70
  targetMemoryUtilization: 70
