image:
  repository: 076831690411.dkr.ecr.ap-northeast-2.amazonaws.com/jasoseoai_nextjs
  tag: cdb4889117a92b44df1a227498cba6eb525bcb43
  port: 4000
service:
  name: jasoseoai-nextjs-service
  type: LoadBalancer
  port: 80
  targetPort: 4000
hpa:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilization: 70
  targetMemoryUtilization: 70
