image:
  repository: 076831690411.dkr.ecr.ap-northeast-2.amazonaws.com/jasoseoai_nestjs
  tag: 46c03c5884bcf06bfb31ff89b94f742ed51a0589
  port: 4050
service:
  name: jasoseoai-nestjs-service
  type: LoadBalancer
  port: 80
  targetPort: 4050
hpa:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilization: 70
  targetMemoryUtilization: 70
