image:
  repository: 076831690411.dkr.ecr.ap-northeast-2.amazonaws.com/jasoseoai_nestjs
  tag: daefe6e9caa3e657f84d6c0fc18152c1247e4127
  port: 4050
service:
  name: jasoseoai-nestjs-service
  type: LoadBalancer
  port: 80
  targetPort: 4050
hpa:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilization: 70
  targetMemoryUtilization: 70
