image:
  repository: 076831690411.dkr.ecr.ap-northeast-2.amazonaws.com/jasoseoai_nestjs
  tag: ec270642e32fb6f3b8f01c3d1b5a38fae36a71ce
  port: 4050
service:
  name: jasoseoai-nestjs-service
  type: LoadBalancer
  port: 80
  targetPort: 4050
hpa:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilization: 70
  targetMemoryUtilization: 70
